== Preface

This document describes an Advanced Interrupt Architecture for RISC-V systems.
This specification was ratified by the International Association in June
of 2023.

The table below indicates which chapters of this document specify
extensions to the ISA (instruction set architecture) and which are
non-ISA.

[cols="<,^",options="header",]
|===
|Chapter |ISA?
|1. Introduction |—
|2. Control and Status Registers (CSRs) Added to Harts |Yes
|3. Incoming MSI Controller (IMSIC) |Yes
|4. Advanced Platform-Level Interrupt Controller (APLIC) |No
|5. Interrupts for Machine and Supervisor Levels |Yes
|6. Interrupts for Virtual Machines (VS Level) |Yes
|7. Interprocessor Interrupts (IPIs) |No
|8. IOMMU Support for MSIs to Virtual Machines |No
|===

=== Changes for the ratified version 1.0

Resolved some inconsistencies in <<CSRs>> about when
to raise a virtual instruction exception versus an illegal instruction
exception.

=== Changes for RC6 (Ratification Candidate 6)

Resolved some inconsistencies in <<CSRs>> about when
to raise a virtual instruction exception versus an illegal instruction
exception.

=== Changes for RC5

Better aligned the rules for indirectly accessed registers with the
hypervisor extension and with forthcoming extension Smcsrind/Sscsrind.
In particular, when `vsiselect` has a reserved value, attempts to access `sireg` from a
virtual machine (VS or VU-mode) should preferably raise an illegal
instruction exception instead of a virtual instruction exception.

Added clarification about the term _IOMMU_ used in <<IOMMU>>.

Added clarification about MSI write replaced by MRIF update and notice
MSI sent after the update.

=== Changes for RC4

For alignment with other forthcoming RISC-V ISA extensions, the widths of the
indirect-access CSRs, `miselect`, `mireg`, `siselect`, `sireg`, `vsiselect`, and `vsireg` were changed to all be the current
XLEN rather than being tied to their respective privilege levels
(previously MXLEN for `miselect` and `mireg`, SXLEN for `siselect` and `sireg`, and VSXLEN for `vsiselect` and `vsireg`).

Changed the description (but not the actual function) of _high-half_
CSRs and their partner CSRs to match the latest RISC-V Privileged ISA
specification. (An example of a high-half CSR is `miph`, and its partner here
is `mip`.)

=== Changes for RC3

Removed the still-draft Duo-PLIC chapter to a separate document.

Allocated major interrupts 35 and 43 for signaling RAS events
(<<majorIntrs>>).

In <<virtIntrs-S>> added the options for
bits 1 and 9 to be writable in CSR , and specified the effects of
setting each of these bits.

Upgraded <<IOMMU>> ("IOMMU Support") to the _frozen_ state.

=== Changes for RC2

Clarified that field IID of CSR must support all unsigned integer values
of the number of bits implemented for that field, and that writes to
always set IID in the most straightforward way.

A comment was added to <<IPIs>> warning about the
possible need for FENCE instructions when IPIs are sent to other harts
by writing MSIs to those harts’ IMSICs.